Bucket stats count shows 'size' and 'size_actual' as same with Motr a…
Seagate/cortx-rgw pull request #284
Opened 2022-06-10 09:20 UTC by Diwakar92

…s backend.

Signed-off-by: Diwakar92 <diwakar.kumar@seagate.com>

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-06-10 10:48 UTC, sachinpunadikar commented on src/cls/rgw/cls_rgw_types.h
> +  uint64_t actual_size;
rename variable actual_size -> size_rounded

2022-06-10 10:50 UTC, sachinpunadikar commented on src/rgw/rgw_sal_motr.cc
> +  // uint64_t lid = M0_OBJ_LAYOUT_ID(source->mobj->ob_attr.oa_layout_id);
remove these lines

2022-06-10 10:52 UTC, sachinpunadikar requested changes
work on comments

2022-06-12 16:34 UTC, jjxsg commented on src/rgw/rgw_obj_manifest.h
> +  uint64_t actual_size{0};
Add a comment stating what `actual_size` represents.

2022-06-12 16:38 UTC, jjxsg commented on src/rgw/rgw_sal_motr.cc
> +  uint64_t size_rounded = roundup(ent.meta.size, unit_sz);
Can we create a function which accepts `size` as input and returns the `rounded_size`?

2022-06-14 04:40 UTC, sumedhak27 commented
Changes are addressed via https://github.com/Seagate/cortx-rgw/pull/292.
Closing the PR.

2022-06-14 04:40 UTC, closed without merging