rgw_sal_motr : [CORTX-31446] Copy-object: send keep alive to client to avoid req timeout
Seagate/cortx-rgw pull request #332
Opened 2022-06-27 09:04 UTC by pranavPawar07

…
Ticket: https://jts.seagate.com/browse/CORTX-31446

Problem Description:
Timeout error for large-sized(more than 3GB) copy-object operation.

Problem Solution:
Call the RGWCopyObj::progress_cb after writing every part, which sends the partial response to the client so that it does not time out.

Signed-off-by: Pranav Diliprao Pawar <pranav.pawar@seagate.com>

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-06-27 09:50 UTC, sjain09 requested changes
One comment

2022-06-27 10:03 UTC, pranavPawar07 commented on src/rgw/rgw_sal_motr.cc
> +  if(this->get_key().get_oid() == dest_object->get_key().get_oid())
Done. please check

2022-06-27 10:05 UTC, sjain09 approved these changes
LGTM

2022-06-28 07:23 UTC, DPG17 approved these changes

2022-06-28 09:10 UTC, merged

2022-06-28 09:48 UTC, andriytk commented on src/rgw/rgw_sal_motr.cc
> +    if(progress_CB){
Style: should be `if (..) {`.