rgw_rest_user_policy.cc[CORTX-32037]:Put user policy with no statement is accepted
Seagate/cortx-rgw pull request #347
Opened 2022-07-12 04:50 UTC by Diwakar92

Problem : Put user policy with no statement is accepted
Solution : Checked if policy document doesn't contain any statement then returned "MalformedPolicyDocument".

2022-07-12 06:52 UTC, sachinpunadikar commented on src/rgw/rgw_rest_user_policy.cc
> -    s->formatter->open_object_section("GetUserPolicyResponse");
Changes from GetUserPolicy methid should not be part of this PR

2022-07-12 06:53 UTC, sachinpunadikar requested changes
work on comment, actual fix for the issue looks good to me

2022-07-14 05:36 UTC, vastradparayya approved these changes
+1

2022-07-14 05:39 UTC, sachinpunadikar approved these changes
LGTM

2022-07-18 07:21 UTC, jjxsg commented on src/rgw/rgw_rest_user_policy.cc
> +      ldpp_dout(this, 20) << "Empty statements in policy document." << dendl;
```suggestion
      ldpp_dout(this, 20) << "ERROR: Empty statement in policy document." << dendl;
```

2022-12-21 05:56 UTC, closed without merging