Fix for RGW admin tool  with motr (user info)
Seagate/cortx-rgw pull request #68
Opened 2022-02-01 14:26 UTC by sanalpk

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [ ] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`

</details>

2022-02-02 03:52 UTC, sumedhak27 commented on src/common/options/rgw.yaml.in
> +  desc: experimental Option to set my Motr fid
```suggestion
  desc: Motr FID for admin-level access.
```

2022-02-02 03:56 UTC, sumedhak27 commented on src/rgw/rgw_admin.cc
> +std::string rgw_store = "rados";
```suggestion
    std::string rgw_store = "rados";
```

2022-02-02 03:58 UTC, sumedhak27 commented on src/rgw/rgw_sal_motr.cc
> +    ldout(cct, 0) << "INFO: motr profile fid:  " << profile << dendl;
we can increase the log level maybe before the final merge.

2022-02-02 11:45 UTC, jjxsg commented on src/common/options/rgw.yaml.in
> +- name: admin_motr_fid
We should have an entry for `admin_motr_endpoint` as well in `rgw.yaml.in`

2022-02-03 07:19 UTC, jjxsg commented on src/common/options/rgw.yaml.in
>  - name: motr_my_endpoint
Please add below entry for radosgw-admin motr endpoint
```
- name: admin_motr_endpoint
  type: str
  level: advanced
  desc: experimental Option to set my Motr endpoint
  long_desc: example value inet:tcp:10.230.241.24@5002
  default: inet:tcp:10.230.241.24@5002
  services:
  - rgw 
```

2022-02-03 07:22 UTC, jjxsg requested changes

2022-02-03 07:22 UTC, jjxsg commented on src/rgw/rgw_sal_motr.cc
> +    }
Please add admin endpoint in if condition
```
 if (init_flags == 0){
        store->conf.mc_process_fid = admin_proc_fid.c_str();
        store->conf.mc_local_addr = admin_proc_ep.c_str();
}
 else{
        store->conf.mc_process_fid = proc_fid.c_str();
        store->conf.mc_local_addr = proc_ep.c_str();
}
```

2022-02-03 07:22 UTC, jjxsg commented on src/rgw/rgw_sal_motr.cc
> +    const auto& admin_proc_fid = g_conf().get_val<std::string>("admin_motr_fid");
Please add
```
const auto &admin_proc_ep = g_conf().get_val<std::string>("admin_motr_endpoint");
```

2022-02-16 06:51 UTC, closed without merging

2022-02-16 07:04 UTC, sanalpk commented
This changes are done as part of another ticket https://github.com/Seagate/cortx-rgw/pull/75/files